@startuml
'https://plantuml.com/sequence-diagram

participant "<<system>>\n:Client" as SH
participant "<<system>>\n:WeatherService" as WS

autoactivate on
autonumber

title Level 1 - Process View. \nUse Case: Instantaneous wind speed and direction reading.

SH -> WS : GET /InstantWind?apiKey=apiKeyValue\n&latitude=latitudeValue&longitude=longitudeValue&hour=hourValue
activate SH

return {"measurement" : measurement, "unit" : unit, "info" : info,\n "links" : links}
deactivate SH

@enduml