@startuml
'https://plantuml.com/class-diagram

left to right direction

package "<<Aggregate>> SunriseOrSunset" {
    object "<<Root>> SunriseOrSunset" as SunriseOrSunset

    object "<<VO>> ValueWSSunriseOrSunset" as ValueWSSunriseOrSunset {
    - measurement : double
    - unit : String
    - info : String
    }

    object "<<VO>> IdSunriseOrSunset" as IdSunriseOrSunset {
    - apiKey : int
    }
}

package "<<Aggregate>> MaxWindOverPeriod" {
    object "<<Root>> MaxWindOverPeriod" as MaxWindOverPeriod

    object "<<VO>> ValueWSMaxWindOverPeriod" as ValueWSMaxWindOverPeriod {
    - measurement : double
    - unit : String
    - info : String
    }

    object "<<VO>> IdMaxWindOverPeriod" as IdMaxWindOverPeriod {
    - apiKey : int
    }
}

package "<<Aggregate>> InstantWind" {
    object "<<Root>> InstantWind" as InstantWind

    object "<<VO>> ValueWSInstantWind" as ValueWSInstantWind {
    - measurement : double
    - unit : String
    - info : String
    }

    object "<<VO>> IdInstantWind" as IdInstantWind {
    - apiKey : int
    }
}

package "<<Aggregate>> InstantTemperature" {
    object "<<Root>> InstantTemperature" as InstantTemperature

    object "<<VO>> ValueWSInstantTemperature" as ValueWSInstantTemperature {
    - measurement : double
    - unit : String
    - info : String
    }

    object "<<VO>> IdInstantTemperature" as IdInstantTemperature {
    - apiKey : int
    }
}

SunriseOrSunset "1" --> "1" ValueWSSunriseOrSunset : has
SunriseOrSunset "1" --> "1" IdSunriseOrSunset : has

MaxWindOverPeriod "1" --> "1" ValueWSMaxWindOverPeriod : has
MaxWindOverPeriod "1" --> "1" IdMaxWindOverPeriod : has

InstantWind "1" --> "1" ValueWSInstantWind : has
InstantWind "1" --> "1" IdInstantWind : has

InstantTemperature "1" --> "1" ValueWSInstantTemperature : has
InstantTemperature "1" --> "1" IdInstantTemperature : has

@enduml